### ISSUE TITLE
User Auth 

### ISSUE THREAD

**Issue by ramahar** [ramahar/Coinography#2]
New account creation, login, and guest/demo login 
- Users can sign up, sign in, log out
- Users can use a demo login to try the site
- Users can't use certain features without logging in

**Comment by andywynkoop** [comment]
- [ ] Why am I getting a 402 payment required error when I try to sign up?
- [ ] You'll need to have more specific error messages than "Invalid Login" - I don't know what I'm doing wrong :'(
- [ ] When I look at your action, it looks like I'm getting a firstname can't be blank and lastname can't be blank error - but I've filled in both of those fields
- [ ] Errors aren't clearing when I click on the nav links to go to different session forms

**Comment by ramahar** [comment]
Hey I fixed all the main issues. Please check it out whenever you have time. Thanks!
